---
- name: Welcome to SOFSYSTEM BootCamp2019 Algeria 
  hosts: all
 
  tasks:
 
  - name: Hostname my machine
    shell: hostname 
    register: result
  - name: My machine 
    debug:
    msg: The hostname machine is {{ result }}
     
