---
- name: Welcome to SOFSYSTEM BootCamp2019 Algeria 
  hosts: all
 
  tasks:
 
  - name: Get FileSystem of my server 
    shell: df -H 
    register: result
  - name: Filesystem of my server  
    debug:
      msg: "Size FileSystem of my server  is : {{ result.stdout }}"
     
