---
- name: Welcome to SOFSYSTEM BootCamp2019 Algeria 
  hosts: localhost
 
  tasks:
  - name: Get FileSystem of my server 
    shell: df -H /home
    register: result
  - name: Filesystem of my server  
    debug:
      msg: "Size FileSystem of my server  on /home  is : {{ result.stdout }}"
      
     
