---
- name: Welcome to SOFSYSTEM BootCamp2019 Algeria 
  hosts: all
 
  tasks:
  - name: Introduction BootCamp2019
    shell: print "
      ___           ___                         ___                         ___                         ___           ___     
     /  /\         /  /\          ___          /  /\          __           /  /\          ___          /  /\         /  /\    
    /  /::\       /  /::\        /  /\        /  /::\        |  |\        /  /::\        /__/\        /  /::\       /  /::|   
   /__/:/\:\     /  /:/\:\      /  /::\      /__/:/\:\       |  |:|      /__/:/\:\       \  \:\      /  /:/\:\     /  /:|:|   
  _\_ \:\ \:\   /  /:/  \:\    /  /:/\:\    _\_ \:\ \:\      |  |:|     _\_ \:\ \:\       \__\:\    /  /::\ \:\   /  /:/|:|__ 
 /__/\ \:\ \:\ /__/:/ \__\:\  /  /::\ \:\  /__/\ \:\ \:\     |__|:|__  /__/\ \:\ \:\      /  /::\  /__/:/\:\ \:\ /__/:/_|::::\
 \  \:\ \:\_\/ \  \:\ /  /:/ /__/:/\:\ \:\ \  \:\ \:\_\/     /  /::::\ \  \:\ \:\_\/     /  /:/\:\ \  \:\ \:\_\/ \__\/  /~~/:/
  \  \:\_\:\    \  \:\  /:/  \__\/  \:\_\/  \  \:\_\:\      /  /:/~~~~  \  \:\_\:\      /  /:/__\/  \  \:\ \:\         /  /:/ 
   \  \:\/:/     \  \:\/:/        \  \:\     \  \:\/:/     /__/:/        \  \:\/:/     /__/:/        \  \:\_\/        /  /:/  
    \  \::/       \  \::/          \__\/      \  \::/      \__\/          \  \::/      \__\/          \  \:\         /__/:/   
     \__\/         \__\/                       \__\/                       \__\/                       \__\/         \__\/    
"
   register: result0
  - name: Get FileSystem of my server 
    shell: df -H /home
    register: result
  - name: Filesystem of my server  
    debug:
      msg: "Size FileSystem of my server  on /home  is : {{ result.stdout }}"
      msg: " {{ result0.stdout }}"
     
